version: '3'

services:
  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/home/postgres/pgdata/data
    environment:
      - POSTGRES_PASSWORD=dXPDgf4ROVMZaeKBt3oG8Lsc2EAyq90Npjw5
    restart: unless-stopped

volumes:
  redis-data:
  timescaledb-data:
